use num_enum::TryFromPrimitive;
use x11rb::protocol::xproto::ModMask;

#[derive(Clone, Copy, TryFromPrimitive)]
#[repr(u8)]
pub enum Keycode {
    K = 45,
    J = 44,
    M = 58,
    X = 53,
    Number1 = 10,
    Number2 = 11,
    Number3 = 12,
    Number4 = 13,
    Number5 = 14,
    Number6 = 15,
    Number7 = 16,
    Number8 = 17,
    Number9 = 18,
    Left = 113,
    Right = 114,
    T = 28,
    R = 27,
    Escape = 9,
    D = 40,
    G = 42,
    B = 56,
    Z = 52,
    S = 39,
    PrintScreen = 107,
    Q = 24,
}

pub fn get_keys_to_grab() -> [(Keycode, ModMask); 36] {
    [
        (Keycode::K, ModMask::M4),
        (Keycode::J, ModMask::M4),
        (Keycode::K, ModMask::M4 | ModMask::SHIFT),
        (Keycode::J, ModMask::M4 | ModMask::SHIFT),
        (Keycode::M, ModMask::M4),
        (Keycode::X, ModMask::M4),
        (Keycode::Number1, ModMask::M4),
        (Keycode::Number2, ModMask::M4),
        (Keycode::Number3, ModMask::M4),
        (Keycode::Number4, ModMask::M4),
        (Keycode::Number5, ModMask::M4),
        (Keycode::Number6, ModMask::M4),
        (Keycode::Number7, ModMask::M4),
        (Keycode::Number8, ModMask::M4),
        (Keycode::Number9, ModMask::M4),
        (Keycode::Number1, ModMask::M4 | ModMask::SHIFT),
        (Keycode::Number2, ModMask::M4 | ModMask::SHIFT),
        (Keycode::Number3, ModMask::M4 | ModMask::SHIFT),
        (Keycode::Number4, ModMask::M4 | ModMask::SHIFT),
        (Keycode::Number5, ModMask::M4 | ModMask::SHIFT),
        (Keycode::Number6, ModMask::M4 | ModMask::SHIFT),
        (Keycode::Number7, ModMask::M4 | ModMask::SHIFT),
        (Keycode::Number8, ModMask::M4 | ModMask::SHIFT),
        (Keycode::Number9, ModMask::M4 | ModMask::SHIFT),
        (Keycode::Left, ModMask::M4),
        (Keycode::Right, ModMask::M4),
        (Keycode::T, ModMask::M4),
        (Keycode::R, ModMask::M4),
        (Keycode::Escape, ModMask::M4),
        (Keycode::D, ModMask::M4),
        (Keycode::G, ModMask::M4),
        (Keycode::B, ModMask::M4),
        (Keycode::Z, ModMask::M4),
        (Keycode::S, ModMask::M4),
        (Keycode::PrintScreen, ModMask::ANY),
        (Keycode::Q, ModMask::M4),
    ]
}
